(() => {
  const labels={en:{plans:'Subscriptions',reseller:'Reseller',downloads:'Downloads',guide:'Guide',legal:'Legal'},fr:{plans:'Abonnements',reseller:'Revendeur',downloads:'Téléchargements',guide:'Guide',legal:'Mentions légales'},ar:{plans:'الاشتراكات',reseller:'الموزعون',downloads:'التحميلات',guide:'الدليل',legal:'القانونية'}};
  const titles={en:{subscriptions:'Choose your subscription.',reseller:'Grow your IPTV business with confidence.',downloads:'Download your preferred player.',guide:'Your setup guide.',legal:'Legal information.'},fr:{subscriptions:'Choisissez votre abonnement.',reseller:'Développez votre activité IPTV en toute confiance.',downloads:'Téléchargez votre lecteur préféré.',guide:'Votre guide d’installation.',legal:'Informations légales.'},ar:{subscriptions:'اختر اشتراكك.',reseller:'طوّر عملك في IPTV بثقة.',downloads:'حمّل المشغّل المناسب لك.',guide:'دليل الإعداد الخاص بك.',legal:'المعلومات القانونية.'}};
  const parts=location.pathname.split('/').filter(Boolean);const page=(parts.at(-1)||'index').replace('.html','');const local=location.protocol==='file:';const route=slug=>local?`../${slug}.html`:`/${slug}/`;const home=local?'../index.html':'/';
  const oldNav=document.querySelector('nav');if(oldNav)oldNav.remove();
  const links=[['plans','subscriptions'],['reseller','reseller'],['downloads','downloads'],['guide','guide'],['legal','legal']];const navLinks=links.map(([key,slug])=>`<a data-menu="${key}" href="${route(slug)}">${labels.en[key]}</a>`).join('');
  document.body.insertAdjacentHTML('afterbegin',`<header class="sticky top-0 z-50 border-b border-white/10 bg-[#050508]/90 backdrop-blur-2xl"><nav class="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><a href="${home}" class="font-bold text-lg">MEGA <span class="text-red-600">OTT</span> <span class="text-yellow-500">PRO</span></a><div class="hidden items-center gap-5 text-sm text-zinc-300 md:flex">${navLinks}</div><div class="flex items-center gap-2"><select id="megaLanguage" class="rounded-lg border border-white/10 bg-white/5 px-2 py-2 text-xs text-white"><option value="en">EN</option><option value="fr">FR</option><option value="ar">العربية</option></select><button id="megaMenuButton" class="rounded-lg border border-white/10 px-3 py-2 text-sm md:hidden">☰</button></div></nav><div id="megaMobileMenu" class="hidden border-t border-white/10 px-5 py-3 text-sm text-zinc-200 md:hidden"><div class="grid gap-2">${navLinks}</div></div></header>`);
  const apply=lang=>{const text=labels[lang]||labels.en;document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.querySelectorAll('[data-menu]').forEach(x=>x.textContent=text[x.dataset.menu]);const h1=document.querySelector('main h1');if(h1&&titles[lang]?.[page])h1.textContent=titles[lang][page];document.getElementById('megaLanguage').value=lang;try{localStorage.setItem('megaLanguage',lang)}catch{}};
  document.getElementById('megaLanguage').addEventListener('change',e=>apply(e.target.value));document.getElementById('megaMenuButton').addEventListener('click',()=>document.getElementById('megaMobileMenu').classList.toggle('hidden'));let saved='en';try{saved=localStorage.getItem('megaLanguage')||'en'}catch{}apply(saved);
  document.body.insertAdjacentHTML('beforeend','<aside class="fixed bottom-4 right-4 z-50 flex gap-2"><a href="https://wa.me/212670779271" class="rounded-full bg-green-500 px-4 py-3 text-sm font-bold text-white shadow-lg">WhatsApp</a><a href="https://t.me/premiumiptvpanelscom" class="rounded-full bg-sky-500 px-4 py-3 text-sm font-bold text-white shadow-lg">Telegram</a><a href="mailto:support@reselleriptv.com" class="hidden rounded-full bg-zinc-700 px-4 py-3 text-sm font-bold text-white shadow-lg sm:block">Email</a></aside>');
})();
